version: "3"
services:
  php:
    build: ./docker/php/8.0
    entrypoint: php
    volumes:
      - .:/home/alpine
    working_dir: /home/alpine

  composer:
    build: ./docker/php/8.0
    entrypoint: composer
    volumes:
      - .:/home/alpine
    working_dir: /home/alpine

  app:
    build: ./docker/php/8.0
    tty: true
    volumes:
      - .:/home/ubuntu/app
    working_dir: /home/ubuntu/app
